"""Add current_reconciling_tx_id to users table

Revision ID: c670c422fa47
Revises: 3e6467493711
Create Date: 2025-09-16 13:37:08.947262

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c670c422fa47"
down_revision = "3e6467493711"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the missing current_reconciling_tx_id column to users table
    op.add_column(
        "users", sa.Column("current_reconciling_tx_id", sa.String(255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the current_reconciling_tx_id column from users table
    op.drop_column("users", "current_reconciling_tx_id")
    # ### end Alembic commands ###
