"""Add id column to Transactions table

Revision ID: d6d7c1423fb2
Revises: c670c422fa47
Create Date: 2025-09-16 15:41:47.548841

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d6d7c1423fb2"
down_revision = "c670c422fa47"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE Transactions_id_seq")
    op.add_column(
        "Transactions",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('Transactions_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
    )
    op.add_column(
        "Transactions",
        sa.Column("tx_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_constraint("Transactions_pkey", "Transactions", type_="primary")
    op.create_primary_key("Transactions_pkey", "Transactions", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("Transactions_pkey", "Transactions", type_="primary")
    op.create_primary_key("Transactions_pkey", "Transactions", ["user_id"])
    op.drop_column("Transactions", "tx_id")
    op.drop_column("Transactions", "id")
    op.execute("DROP SEQUENCE Transactions_id_seq")
    # ### end Alembic commands ###
